---
build_from:
  amd64: "ghcr.io/hassio-addons/base/amd64:18.0.3"
  armhf: "ghcr.io/hassio-addons/base/armhf:18.0.3"
  armv7: "ghcr.io/hassio-addons/base/armv7:18.0.3"
  aarch64: "ghcr.io/hassio-addons/base/aarch64:18.0.3"
  i386: "ghcr.io/hassio-addons/base/i386:18.0.3"
