---
build_from:
  amd64: "ghcr.io/hassio-addons/base/amd64:16.2.1"
  armhf: "ghcr.io/hassio-addons/base/armhf:16.2.1"
  armv7: "ghcr.io/hassio-addons/base/armv7:16.2.1"
  aarch64: "ghcr.io/hassio-addons/base/aarch64:16.2.1"
  i386: "ghcr.io/hassio-addons/base/i386:16.2.1"
