---
build_from:
  amd64: "ghcr.io/hassio-addons/base/amd64:14.0.5"
  armhf: "ghcr.io/hassio-addons/base/armhf:14.0.5"
  armv7: "ghcr.io/hassio-addons/base/armv7:14.0.5"
  aarch64: "ghcr.io/hassio-addons/base/aarch64:14.0.5"
  i386: "ghcr.io/hassio-addons/base/i386:14.0.5"
