---
build_from:
  amd64: "ghcr.io/hassio-addons/base/amd64:13.1.4"
  armhf: "ghcr.io/hassio-addons/base/armhf:13.1.4"
  armv7: "ghcr.io/hassio-addons/base/armv7:13.1.4"
  aarch64: "ghcr.io/hassio-addons/base/aarch64:13.1.4"
  i386: "ghcr.io/hassio-addons/base/i386:13.1.4"
