---
build_from:
  amd64: "ghcr.io/hassio-addons/base/amd64:16.3.5"
  armhf: "ghcr.io/hassio-addons/base/armhf:16.3.5"
  armv7: "ghcr.io/hassio-addons/base/armv7:16.3.5"
  aarch64: "ghcr.io/hassio-addons/base/aarch64:16.3.5"
  i386: "ghcr.io/hassio-addons/base/i386:16.3.5"
