---
build_from:
  amd64: "ghcr.io/hassio-addons/base/amd64:18.1.0"
  armhf: "ghcr.io/hassio-addons/base/armhf:18.1.0"
  armv7: "ghcr.io/hassio-addons/base/armv7:18.1.0"
  aarch64: "ghcr.io/hassio-addons/base/aarch64:18.1.0"
  i386: "ghcr.io/hassio-addons/base/i386:18.1.0"
