---
name: freshrss
version: dev
slug: freshrss
description: freshrss description
url: "https://github.com/einschmidt/addon-yarr"
panel_icon: "mdi:rss-box"
arch:
  - i386
  - armhf
  - armv7
  - amd64
  - aarch64
ports:
  80/tcp: 7077
ports_description:
  80/tcp: Web interface
init: false
map:
  - ssl
options:
  base_url: ""
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
  base_url: str
