---
name: FreshRSS
version: 16
slug: freshrss
description: A free, self-hostable feed aggregator
url: "https://github.com/einschmidt/addon-freshrss"
panel_icon: "mdi:rss-box"
arch:
  - i386
  - armhf
  - armv7
  - amd64
  - aarch64
ports:
  80/tcp: 7077
ports_description:
  80/tcp: Web interface
init: false
ingress: true
ingress_stream: true
ingress_port: 8099
map:
  - type: ssl
  - type: addon_config
    read_only: false
options:
  base_url: ""
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
  base_url: str
